### ISSUE TITLE
Missing Sqlite3 Implementation

### ISSUE THREAD

**Issue by paradise-runner** [ErikKaum/runner#1]
I suspect this is similar to the weird dependency chain that happens in go land when trying to use sqlite in go land, but the I try to import sqlite3 I get the error `ModuleNotFoundError: No module named '_sqlite3'`. Is it just that the process for loading up sqlite3 uses too much weird C code for it to be properly handled in the standard way? Would it be worthwhile to attempt to recompile the python with this compatibility? This is some great work! So excited to try and use this for some of my projects!

**Comment by ErikKaum** [comment]
Hi @paradise-runner 👋 

Glad to hear that you've found this project useful 🙌 

Yeah since `sqlite3` has a native component (written in C) it's not straight forward to support it in this runtime. Basically the way to go would be to compile the Python interpreter together with the native part of sqlite3 into one `.wasm` target.

The downside is that for every dependency (that has a native component) that you might need, you'd need to compile it ahead of time into the one big `.wasm` target. So that's not ideal.

Also you'd need to verify that `sqlite3` can be compiled to wasm in the first place as well.

I'll continue to tinker with this and see if I could provide some nice way of getting native dependencies working, even in some hacky way 👍

**Comment by paradise-runner** [comment]
I'll close this out then and continue to work with it. Thanks again!
